'use client';

import { forwardRef, useState, useEffect } from 'react';
import { InvoiceFormData, calculateTotal, Language } from '@/lib/schemas';
import { formatCurrency, generateInvoiceNumber } from '@/lib/utils';
import type { ReceiptDimension } from './InvoiceForm';

const dimensionWidths: Record<ReceiptDimension, number> = {
  standard: 400,
  compact: 320,
  thermal: 280,
  a4: 595,
};

// Translation strings for English and Tagalog
const translations: Record<Language, {
  officialReceipt: string;
  receiptNumber: string;
  date: string;
  customer: string;
  item: string;
  qty: string;
  amount: string;
  total: string;
  notes: string;
  thankYou: string;
  generatedBy: string;
  guestCustomer: string;
}> = {
  en: {
    officialReceipt: 'Official Receipt',
    receiptNumber: 'Receipt #',
    date: 'Date',
    customer: 'Customer',
    item: 'ITEM',
    qty: 'QTY',
    amount: 'AMOUNT',
    total: 'TOTAL',
    notes: 'Notes',
    thankYou: 'Thank you for your business!',
    generatedBy: 'Generated by Resibilis',
    guestCustomer: 'Guest Customer',
  },
  tl: {
    officialReceipt: 'Opisyal na Resibo',
    receiptNumber: 'Resibo #',
    date: 'Petsa',
    customer: 'Customer',
    item: 'BAGAY',
    qty: 'BILANG',
    amount: 'HALAGA',
    total: 'KABUUAN',
    notes: 'Mga Tala',
    thankYou: 'Salamat sa inyong suporta!',
    generatedBy: 'Ginawa ng Resibilis',
    guestCustomer: 'Guest Customer',
  },
};

interface InvoicePreviewProps {
  data: InvoiceFormData;
  invoiceNumber?: string;
  dimension?: ReceiptDimension;
}

/**
 * InvoicePreview Component
 * 
 * IMPORTANT: This component maintains white background (#FFFFFF) and black text
 * regardless of the app's dark/light mode. This ensures receipts are always
 * readable when printed or shared via messaging apps.
 */
export const InvoicePreview = forwardRef<HTMLDivElement, InvoicePreviewProps>(
  ({ data, invoiceNumber, dimension = 'standard' }, ref) => {
    const [receiptNumber, setReceiptNumber] = useState<string>('');
    const [currentDate, setCurrentDate] = useState<string>('');
    
    // Get language from data, default to 'en'
    const language = data.language || 'en';
    const t = translations[language];
    
    // Generate these values only on client to avoid hydration mismatch
    useEffect(() => {
      setReceiptNumber(invoiceNumber || generateInvoiceNumber());
      setCurrentDate(new Date().toLocaleDateString(language === 'tl' ? 'fil-PH' : 'en-PH', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      }));
    }, [invoiceNumber, language]);
    
    const total = calculateTotal(data.items);
    const currencySymbol = data.currency === 'PHP' ? '₱' : '$';
    const width = dimensionWidths[dimension];
    
    // Use business name if provided, otherwise default to "RESIBILIS"
    const businessName = data.businessName?.trim() || 'RESIBILIS';

    return (
      <div
        ref={ref}
        style={{
          // Force white background for printing/export - NEVER dark mode
          backgroundColor: '#FFFFFF',
          color: '#000000',
          width: `${width}px`,
          boxSizing: 'border-box',
          padding: '16px',
          fontFamily: "'Courier New', 'Consolas', monospace",
          fontSize: dimension === 'thermal' ? '12px' : dimension === 'compact' ? '13px' : '14px',
        }}
      >
        {/* Receipt Paper */}
        <div
          style={{
            backgroundColor: '#FFFFFF',
            border: '1px solid #e5e7eb',
            borderRadius: '8px',
            padding: '24px',
            boxSizing: 'border-box',
            width: '100%',
          }}
        >
          {/* Header */}
          <div style={{ textAlign: 'center', borderBottom: '2px dashed #d1d5db', paddingBottom: '16px', marginBottom: '16px' }}>
            <h1
              style={{ color: '#000000', fontSize: '24px', fontWeight: 'bold', margin: 0, letterSpacing: '-0.5px' }}
            >
              {businessName}
            </h1>
            <p style={{ color: '#6b7280', fontSize: '12px', marginTop: '4px', margin: '4px 0 0 0' }}>
              {t.officialReceipt}
            </p>
          </div>

          {/* Receipt Info */}
          <div style={{ fontSize: '14px', marginBottom: '16px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
              <span style={{ color: '#6b7280' }}>{t.receiptNumber}:</span>
              <span style={{ color: '#000000', fontWeight: 500 }}>
                {receiptNumber || '---'}
              </span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
              <span style={{ color: '#6b7280' }}>{t.date}:</span>
              <span style={{ color: '#000000', fontWeight: 500 }}>
                {currentDate || '---'}
              </span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: '#6b7280' }}>{t.customer}:</span>
              <span
                style={{ color: '#000000', fontWeight: 500, textAlign: 'right', maxWidth: '60%', wordBreak: 'break-word' }}
              >
                {data.customerName || t.guestCustomer}
              </span>
            </div>
          </div>

          {/* Divider */}
          <div
            style={{ borderTop: '1px dashed #d1d5db', margin: '16px 0' }}
          />

          {/* Items Header */}
          <div
            style={{ 
              display: 'flex', 
              fontSize: '12px', 
              fontWeight: 600, 
              color: '#6b7280',
              marginBottom: '8px'
            }}
          >
            <span style={{ flex: 1 }}>{t.item}</span>
            <span style={{ width: '50px', textAlign: 'center' }}>{t.qty}</span>
            <span style={{ width: '80px', textAlign: 'right' }}>{t.amount}</span>
          </div>

          {/* Items List */}
          <div>
            {data.items.map((item, index) => {
              const qty = Number(item.qty) || 0;
              const price = Number(item.price) || 0;
              const lineTotal = qty * price;
              return (
                <div
                  key={item.id || index}
                  style={{ 
                    display: 'flex', 
                    fontSize: '14px', 
                    color: '#000000',
                    marginBottom: '8px'
                  }}
                >
                  <span style={{ flex: 1, paddingRight: '8px', wordBreak: 'break-word' }}>
                    {item.item || `Item ${index + 1}`}
                  </span>
                  <span style={{ width: '50px', textAlign: 'center' }}>{qty}</span>
                  <span style={{ width: '80px', textAlign: 'right', fontWeight: 500 }}>
                    {currencySymbol}{lineTotal.toFixed(2)}
                  </span>
                </div>
              );
            })}
          </div>

          {/* Divider */}
          <div
            style={{ borderTop: '1px dashed #d1d5db', margin: '16px 0' }}
          />

          {/* Total */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '18px', fontWeight: 'bold' }}>
            <span style={{ color: '#000000' }}>{t.total}</span>
            <span style={{ color: '#000000' }}>
              {formatCurrency(total, data.currency)}
            </span>
          </div>

          {/* Notes */}
          {data.notes && (
            <>
              <div
                style={{ borderTop: '1px dashed #d1d5db', margin: '16px 0' }}
              />
              <div style={{ fontSize: '14px' }}>
                <p style={{ color: '#6b7280', fontWeight: 500, marginBottom: '4px', margin: '0 0 4px 0' }}>
                  {t.notes}:
                </p>
                <p
                  style={{ color: '#000000', whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0 }}
                >
                  {data.notes}
                </p>
              </div>
            </>
          )}

          {/* Footer */}
          <div
            style={{ borderTop: '1px dashed #d1d5db', marginTop: '16px', paddingTop: '16px', textAlign: 'center', fontSize: '12px', color: '#9ca3af' }}
          >
            <p style={{ margin: 0 }}>{t.thankYou}</p>
            <p style={{ margin: '8px 0 0 0' }}>{t.generatedBy}</p>
          </div>
        </div>
      </div>
    );
  }
);

InvoicePreview.displayName = 'InvoicePreview';
