'use client';

import { forwardRef, useState, useEffect } from 'react';
import { InvoiceFormData, calculateTotal, Language } from '@/lib/schemas';
import { formatCurrency, generateInvoiceNumber } from '@/lib/utils';
import { calculateReceiptTotal } from '@/lib/utils/taxDiscount';
import type { ReceiptDimension } from './InvoiceForm';

const dimensionWidths: Record<ReceiptDimension, number> = {
  standard: 400,
  compact: 320,
  thermal: 280,
  a4: 595,
};

// Translation strings for English and Tagalog
const translations: Record<Language, {
  officialReceipt: string;
  receiptNumber: string;
  date: string;
  customer: string;
  item: string;
  qty: string;
  amount: string;
  subtotal: string;
  discount: string;
  tax: string;
  total: string;
  notes: string;
  thankYou: string;
  generatedBy: string;
  guestCustomer: string;
}> = {
  en: {
    officialReceipt: 'Official Receipt',
    receiptNumber: 'Receipt #',
    date: 'Date',
    customer: 'Customer',
    item: 'ITEM',
    qty: 'QTY',
    amount: 'AMOUNT',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    total: 'TOTAL',
    notes: 'Notes',
    thankYou: 'Thank you for your support!',
    generatedBy: 'Generated by Resibilis',
    guestCustomer: 'Guest Customer',
  },
  tl: {
    officialReceipt: 'Opisyal na Resibo',
    receiptNumber: 'Resibo #',
    date: 'Petsa',
    customer: 'Customer',
    item: 'BAGAY',
    qty: 'BILANG',
    amount: 'HALAGA',
    subtotal: 'Subtotal',
    discount: 'Diskwento',
    tax: 'Buwis',
    total: 'KABUUAN',
    notes: 'Mga Tala',
    thankYou: 'Salamat sa inyong suporta!',
    generatedBy: 'Ginawa ng Resibilis',
    guestCustomer: 'Guest Customer',
  },
};

interface InvoicePreviewProps {
  data: InvoiceFormData;
  invoiceNumber?: string;
  dimension?: ReceiptDimension;
}

/**
 * InvoicePreview Component
 * 
 * IMPORTANT: This component maintains white background (#FFFFFF) and black text
 * regardless of the app's dark/light mode. This ensures receipts are always
 * readable when printed or shared via messaging apps.
 */
export const InvoicePreview = forwardRef<HTMLDivElement, InvoicePreviewProps>(
  ({ data, invoiceNumber, dimension = 'standard' }, ref) => {
    const [receiptNumber, setReceiptNumber] = useState<string>('');
    const [currentDate, setCurrentDate] = useState<string>('');
    
    // Get language from data, default to 'en'
    const language = data.language || 'en';
    const t = translations[language];
    
    // Generate these values only on client to avoid hydration mismatch
    useEffect(() => {
      setReceiptNumber(invoiceNumber || generateInvoiceNumber());
      setCurrentDate(new Date().toLocaleDateString(language === 'tl' ? 'fil-PH' : 'en-PH', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      }));
    }, [invoiceNumber, language]);
    
    // Calculate totals with tax and discount - wrapped in try-catch
    let calculation;
    let calculationError: string | null = null;
    
    try {
      calculation = calculateReceiptTotal(
        data.items.map((item) => ({
          price: Number(item.price) || 0,
          qty: Number(item.qty) || 0,
        })),
        {
          taxPercent: data.taxPercent || 0,
          discountType: data.discountType || 'percentage',
          discountValue: data.discountValue || 0,
        }
      );
    } catch (error) {
      // Fallback to safe calculation if error occurs
      calculationError = error instanceof Error ? error.message : 'Calculation error';
      calculation = {
        subtotal: 0,
        taxAmount: 0,
        discountAmount: 0,
        total: 0,
      };
    }
    
    const currencySymbol = data.currency === 'PHP' ? '₱' : '$';
    const width = dimensionWidths[dimension];

    const typography = {
      standard: {
        base: 14,
        muted: 12,
        header: 24,
        info: 14,
        itemHeader: 12,
        itemRow: 14,
        total: 18,
        footer: 12,
        paddingOuter: 16,
        paddingInner: 24,
        dividerMargin: 16,
        qtyCol: 50,
        amtCol: 80,
      },
      compact: {
        base: 12,
        muted: 11,
        header: 20,
        info: 12,
        itemHeader: 11,
        itemRow: 12,
        total: 16,
        footer: 11,
        paddingOuter: 14,
        paddingInner: 18,
        dividerMargin: 12,
        qtyCol: 46,
        amtCol: 72,
      },
      thermal: {
        base: 11,
        muted: 10,
        header: 18,
        info: 11,
        itemHeader: 10,
        itemRow: 11,
        total: 14,
        footer: 10,
        paddingOuter: 12,
        paddingInner: 16,
        dividerMargin: 10,
        qtyCol: 42,
        amtCol: 68,
      },
      a4: {
        base: 15,
        muted: 12,
        header: 26,
        info: 15,
        itemHeader: 12,
        itemRow: 15,
        total: 20,
        footer: 12,
        paddingOuter: 18,
        paddingInner: 28,
        dividerMargin: 18,
        qtyCol: 54,
        amtCol: 90,
      },
    }[dimension];
    
    // Use business name if provided, otherwise default to "RESIBILIS"
    const businessName = data.businessName?.trim() || 'RESIBILIS';

    return (
      <div
        ref={ref}
        className="receipt-shadow"
        style={{
          // Force white background for printing/export - NEVER dark mode
          backgroundColor: '#FFFFFF',
          color: '#000000',
          width: `${width}px`,
          boxSizing: 'border-box',
          padding: `${typography.paddingOuter}px`,
          fontFamily: "'Courier New', 'Consolas', monospace",
          fontSize: `${typography.base}px`,
          boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        }}
      >
        {/* Receipt Paper */}
        <div
          style={{
            backgroundColor: 'transparent',
            border: '1px solid #e5e7eb',
            borderRadius: '8px',
            padding: `${typography.paddingInner}px`,
            boxSizing: 'border-box',
            width: '100%',
          }}
        >
          {/* Calculation Error Warning */}
          {calculationError && (
            <div style={{ 
              backgroundColor: '#fef2f2', 
              border: '2px solid #fca5a5',
              borderRadius: '6px',
              padding: '12px',
              marginBottom: `${typography.dividerMargin}px`,
              textAlign: 'center'
            }}>
              <p style={{ color: '#dc2626', fontSize: `${typography.muted}px`, fontWeight: 600, margin: 0 }}>
                ⚠️ {calculationError}
              </p>
              <p style={{ color: '#991b1b', fontSize: `${typography.muted - 1}px`, margin: '4px 0 0 0' }}>
                Please check tax and discount values
              </p>
            </div>
          )}

          {/* Header */}
          <div style={{ textAlign: 'center', borderBottom: '2px dashed #d1d5db', paddingBottom: `${typography.dividerMargin}px`, marginBottom: `${typography.dividerMargin}px` }}>
            <h1
              style={{ color: '#000000', fontSize: `${typography.header}px`, fontWeight: 'bold', margin: 0, letterSpacing: '-0.5px' }}
            >
              {businessName}
            </h1>
            <p style={{ color: '#6b7280', fontSize: `${typography.muted}px`, marginTop: '4px', margin: '4px 0 0 0' }}>
              {t.officialReceipt}
            </p>
          </div>

          {/* Receipt Info */}
          <div style={{ fontSize: `${typography.info}px`, marginBottom: `${typography.dividerMargin}px` }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
              <span style={{ color: '#6b7280' }}>{t.receiptNumber}:</span>
              <span style={{ color: '#000000', fontWeight: 500 }}>
                {receiptNumber || '---'}
              </span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
              <span style={{ color: '#6b7280' }}>{t.date}:</span>
              <span style={{ color: '#000000', fontWeight: 500 }}>
                {currentDate || '---'}
              </span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: '#6b7280' }}>{t.customer}:</span>
              <span
                style={{ color: '#000000', fontWeight: 500, textAlign: 'right', maxWidth: '60%', wordBreak: 'break-word' }}
              >
                {data.customerName || t.guestCustomer}
              </span>
            </div>
          </div>

          {/* Divider */}
          <div
            style={{ borderTop: '1px dashed #d1d5db', margin: `${typography.dividerMargin}px 0` }}
          />

          {/* Items Header */}
          <div
            style={{ 
              display: 'flex', 
              fontSize: `${typography.itemHeader}px`, 
              fontWeight: 600, 
              color: '#6b7280',
              marginBottom: '8px'
            }}
          >
            <span style={{ flex: 1 }}>{t.item}</span>
            <span style={{ width: `${typography.qtyCol}px`, textAlign: 'center' }}>{t.qty}</span>
            <span style={{ width: `${typography.amtCol}px`, textAlign: 'right' }}>{t.amount}</span>
          </div>

          {/* Items List */}
          <div>
            {data.items.map((item, index) => {
              const qty = Number(item.qty) || 0;
              const price = Number(item.price) || 0;
              const lineTotal = qty * price;
              return (
                <div
                  key={item.id || index}
                  style={{ 
                    display: 'flex', 
                    fontSize: `${typography.itemRow}px`, 
                    color: '#000000',
                    marginBottom: '8px'
                  }}
                >
                  <span style={{ flex: 1, paddingRight: '8px', wordBreak: 'break-word' }}>
                    {item.item || `Item ${index + 1}`}
                  </span>
                  <span style={{ width: `${typography.qtyCol}px`, textAlign: 'center' }}>{qty}</span>
                  <span style={{ width: `${typography.amtCol}px`, textAlign: 'right', fontWeight: 500 }}>
                    {currencySymbol}{lineTotal.toFixed(2)}
                  </span>
                </div>
              );
            })}
          </div>

          {/* Divider */}
          <div
            style={{ borderTop: '1px dashed #d1d5db', margin: `${typography.dividerMargin}px 0` }}
          />

          {/* Calculation Breakdown */}
          <div style={{ fontSize: `${typography.itemRow}px` }}>
            {/* Subtotal */}
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '6px' }}>
              <span style={{ color: '#6b7280' }}>{t.subtotal}:</span>
              <span style={{ color: '#000000', fontWeight: 500 }}>
                {currencySymbol}{calculation.subtotal.toFixed(2)}
              </span>
            </div>
            
            {/* Discount (if applied) */}
            {calculation.discountAmount > 0 && (
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '6px' }}>
                <span style={{ color: '#6b7280' }}>
                  {t.discount}
                  {data.discountType === 'percentage' && ` (${data.discountValue}%)`}:
                </span>
                <span style={{ color: '#16a34a', fontWeight: 500 }}>
                  -{currencySymbol}{calculation.discountAmount.toFixed(2)}
                </span>
              </div>
            )}
            
            {/* Tax (if applied) */}
            {calculation.taxAmount > 0 && (
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '6px' }}>
                <span style={{ color: '#6b7280' }}>
                  {t.tax} ({data.taxPercent}%):
                </span>
                <span style={{ color: '#000000', fontWeight: 500 }}>
                  +{currencySymbol}{calculation.taxAmount.toFixed(2)}
                </span>
              </div>
            )}
          </div>
          
          {/* Divider before total (only if tax or discount applied) */}
          {(calculation.taxAmount > 0 || calculation.discountAmount > 0) && (
            <div
              style={{ borderTop: '1px solid #d1d5db', margin: `${typography.dividerMargin / 2}px 0` }}
            />
          )}

          {/* Total */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: `${typography.total}px`, fontWeight: 'bold' }}>
            <span style={{ color: '#000000' }}>{t.total}</span>
            <span style={{ color: '#000000' }}>
              {currencySymbol}{calculation.total.toFixed(2)}
            </span>
          </div>

          {/* Notes */}
          {data.notes && (
            <>
              <div
                style={{ borderTop: '1px dashed #d1d5db', margin: `${typography.dividerMargin}px 0` }}
              />
              <div style={{ fontSize: `${typography.itemRow}px` }}>
                <p style={{ color: '#6b7280', fontWeight: 500, marginBottom: '4px', margin: '0 0 4px 0' }}>
                  {t.notes}:
                </p>
                <p
                  style={{ color: '#000000', whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0 }}
                >
                  {data.notes}
                </p>
              </div>
            </>
          )}

          {/* Footer */}
          <div
            style={{ borderTop: '1px dashed #d1d5db', marginTop: `${typography.dividerMargin}px`, paddingTop: `${typography.dividerMargin}px`, textAlign: 'center', fontSize: `${typography.footer}px`, color: '#9ca3af' }}
          >
            <p style={{ margin: 0 }}>{t.thankYou}</p>
            <p style={{ margin: '8px 0 0 0' }}>{t.generatedBy}</p>
          </div>
        </div>
      </div>
    );
  }
);

InvoicePreview.displayName = 'InvoicePreview';
