'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Button, Card, CardContent, CardHeader, CardTitle } from '@/components/ui';
import { AuthButton } from '@/components/auth';
import { 
  allTemplates, 
  premiumTemplates,
  ReceiptTemplate,
  defaultTemplate,
} from '@/lib/templates';
import { 
  Check, 
  Crown, 
  Star, 
  Zap, 
  Shield, 
  ArrowLeft,
  CreditCard,
  Smartphone,
  Building2,
  Sparkles,
  Package,
  Save,
  Palette,
  Layout,
  Clock,
  Bell,
} from 'lucide-react';
import { cn } from '@/lib/utils';

// Feature flag for premium purchases
const PREMIUM_ENABLED = false; // Set to true when payment is ready

// Free vs Premium comparison
const planFeatures = {
  free: [
    { feature: 'Generate unlimited receipts', included: true },
    { feature: 'Download as PNG/PDF', included: true },
    { feature: 'Classic receipt template', included: true },
    { feature: 'English & Tagalog language', included: true },
    { feature: 'Custom business name', included: true },
    { feature: 'Save receipt history', included: false, requiresAuth: true },
    { feature: 'Product catalog', included: false, requiresAuth: true },
    { feature: 'Premium templates', included: false },
    { feature: 'Custom branding (logo, colors)', included: false },
    { feature: 'Remove "Generated by Resibilis"', included: false },
  ],
  authenticated: [
    { feature: 'Generate unlimited receipts', included: true },
    { feature: 'Download as PNG/PDF', included: true },
    { feature: 'Classic receipt template', included: true },
    { feature: 'English & Tagalog language', included: true },
    { feature: 'Custom business name', included: true },
    { feature: 'Save receipt history', included: true },
    { feature: 'Product catalog', included: true },
    { feature: 'Premium templates', included: false, note: 'Purchase individually' },
    { feature: 'Custom branding (logo, colors)', included: false },
    { feature: 'Remove "Generated by Resibilis"', included: false },
  ],
  premium: [
    { feature: 'Generate unlimited receipts', included: true },
    { feature: 'Download as PNG/PDF', included: true },
    { feature: 'All premium templates', included: true },
    { feature: 'English & Tagalog language', included: true },
    { feature: 'Custom business name', included: true },
    { feature: 'Save receipt history', included: true },
    { feature: 'Product catalog', included: true },
    { feature: 'Custom branding (logo, colors)', included: true },
    { feature: 'Remove "Generated by Resibilis"', included: true },
    { feature: 'Priority support', included: true },
  ],
};

export function PricingContent() {
  const [selectedPlan, setSelectedPlan] = useState<'free' | 'templates' | 'premium'>('templates');

  return (
    <main className="min-h-screen">
      {/* Header */}
      <div className="bg-gradient-to-b from-green-600 to-emerald-700 text-white py-16 px-4">
        <div className="max-w-5xl mx-auto">
          <Link 
            href="/"
            className="inline-flex items-center gap-2 text-green-100 hover:text-white mb-6 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Generator
          </Link>
          
          <h1 className="text-3xl md:text-4xl font-bold mb-4">
            Simple, Affordable Pricing
          </h1>
          <p className="text-lg text-green-100 max-w-2xl">
            Start free, upgrade when you need more. No hidden fees, no subscriptions required.
            <br />
            <span className="text-sm">Magsimula ng libre, mag-upgrade kung kailangan. Walang nakatagong bayad.</span>
          </p>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 py-12">
        {/* Pricing Cards */}
        <div className="grid md:grid-cols-3 gap-6 -mt-20 mb-12">
          {/* Free Plan */}
          <Card variant="bordered" className="overflow-hidden">
            <CardHeader className="bg-primary-50 dark:bg-primary-900/20 rounded-lg px-4 pt-1">
              <CardTitle className="text-lg ">Free / Libre</CardTitle>
              <p className="text-sm text-primary-600 dark:text-primary-400">Para sa lahat</p>
            </CardHeader>
            <CardContent className="p-6">
              <div className="mb-6">
                <span className="text-4xl font-bold text-foreground">₱0</span>
                <span className="text-primary-600 dark:text-primary-400">/forever</span>
              </div>
              
              <ul className="space-y-3 mb-6">
                {planFeatures.free.slice(0, 7).map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    {item.included ? (
                      <Check className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                    ) : item.requiresAuth ? (
                      <span className="w-4 h-4 text-yellow-500 mt-0.5 flex-shrink-0 text-xs">🔑</span>
                    ) : (
                      <span className="w-4 h-4 text-gray-300 mt-0.5 flex-shrink-0">—</span>
                    )}
                    <span className={cn(
                      item.included ? 'text-primary-700 dark:text-primary-300' : 'text-primary-600/70 dark:text-primary-400/70'
                    )}>
                      {item.feature}
                      {item.requiresAuth && <span className="text-xs text-yellow-600 ml-1">(sign in)</span>}
                    </span>
                  </li>
                ))}
              </ul>

              <Link href="/">
                <Button variant="secondary" className="w-full">
                  Start Free
                </Button>
              </Link>
            </CardContent>
          </Card>

          {/* Individual Templates */}
          <Card variant="bordered" className="overflow-hidden border-green-500 ring-2 ring-green-200 dark:ring-green-800 relative">
            <div className="absolute top-0 right-0 bg-amber-500 text-white text-xs px-3 py-1 rounded-bl-lg font-medium flex items-center gap-1">
              <Clock className="w-3 h-3" />
              COMING SOON
            </div>
            <CardHeader className="bg-green-50 dark:bg-green-900/20 border-b border-green-200 dark:border-green-800 rounded-lg px-4 pt-1">
              <CardTitle className="text-lg flex items-center gap-2">
                <Crown className="w-5 h-5 text-yellow-500" />
                Premium Templates
              </CardTitle>
              <p className="text-sm text-primary-600 dark:text-primary-400">Buy what you need</p>
            </CardHeader>
            <CardContent className="p-6">
              <div className="mb-6">
                <span className="text-4xl font-bold text-foreground">₱50</span>
                <span className="text-primary-600 dark:text-primary-400">-₱100/template</span>
              </div>
              
              <ul className="space-y-3 mb-6">
                <li className="flex items-start gap-2 text-sm">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-primary-700 dark:text-primary-300">
                    <strong>7 premium templates</strong> to choose from
                  </span>
                </li>
                <li className="flex items-start gap-2 text-sm">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-primary-700 dark:text-primary-300">One-time payment, use forever</span>
                </li>
                <li className="flex items-start gap-2 text-sm">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-primary-700 dark:text-primary-300">Professional designs for your brand</span>
                </li>
                <li className="flex items-start gap-2 text-sm">
                  <Check className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-primary-700 dark:text-primary-300">All free features included</span>
                </li>
              </ul>

              <Button variant="secondary" className="w-full" disabled>
                <Clock className="w-4 h-4 mr-2" />
                Coming Soon
              </Button>
            </CardContent>
          </Card>

          {/* Premium Subscription */}
          <Card variant="bordered" className="overflow-hidden">
            <CardHeader className="bg-gradient-to-r from-yellow-50 to-amber-50 dark:from-yellow-900/20 dark:to-amber-900/20 border-b border-yellow-200 dark:border-yellow-800 rounded-lg px-4 pt-1">
              <CardTitle className="text-lg flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-yellow-500" />
                Premium Pro
              </CardTitle>
              <p className="text-sm text-primary-600 dark:text-primary-400">Unlock everything</p>
            </CardHeader>
            <CardContent className="p-6">
              <div className="mb-6">
                <span className="text-4xl font-bold text-foreground">₱299</span>
                <span className="text-primary-600 dark:text-primary-400">/month</span>
              </div>
              
              <ul className="space-y-3 mb-6">
                {planFeatures.premium.slice(0, 7).map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <Check className="w-4 h-4 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-primary-700 dark:text-primary-300">{item.feature}</span>
                  </li>
                ))}
              </ul>

              <Button variant="secondary" className="w-full" disabled>
                Coming Soon
              </Button>
            </CardContent>
          </Card>
        </div>

        {/* Templates Gallery */}
        <section id="templates" className="mb-16 scroll-mt-8">
          <div className="text-center mb-8">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
              Premium Templates
            </h2>
            <p className="text-gray-600 dark:text-gray-400">
              Professional designs to make your receipts stand out
            </p>
            {!PREMIUM_ENABLED && (
              <div className="mt-4 inline-flex items-center gap-2 px-4 py-2 bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300 rounded-full text-sm">
                <Clock className="w-4 h-4" />
                Premium templates coming soon! Sign up to be notified.
              </div>
            )}
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {allTemplates.map((template) => (
              <Card key={template.id} variant="bordered" className="overflow-hidden">
                {/* Template Preview */}
                <div 
                  className="aspect-[3/4] p-3"
                  style={{ backgroundColor: template.styles.backgroundColor }}
                >
                  <div
                    className="h-full rounded"
                    style={{
                      backgroundColor: template.styles.paperBackground,
                      border: template.styles.borderStyle !== 'none' 
                        ? `2px ${template.styles.borderStyle} ${template.styles.borderColor}`
                        : 'none',
                      borderRadius: `${template.styles.borderRadius}px`,
                      padding: '12px',
                    }}
                  >
                    <div 
                      className="text-center mb-2 pb-2"
                      style={{ 
                        borderBottom: template.styles.showHeaderDivider 
                          ? `1px ${template.styles.dividerStyle} ${template.styles.dividerColor}`
                          : 'none',
                      }}
                    >
                      <div 
                        className="font-bold text-xs"
                        style={{ color: template.styles.primaryColor }}
                      >
                        RESIBILIS
                      </div>
                    </div>
                    <div className="space-y-1">
                      {[...Array(4)].map((_, i) => (
                        <div 
                          key={i}
                          className="h-1.5 rounded-full"
                          style={{ 
                            backgroundColor: template.styles.textColor,
                            opacity: 0.2,
                            width: `${100 - i * 15}%`,
                          }}
                        />
                      ))}
                    </div>
                  </div>
                </div>
                
                {/* Template Info */}
                <CardContent className="p-4 border-t border-gray-200 dark:border-gray-700">
                  <h3 className="font-medium text-gray-900 dark:text-white text-sm mb-1">
                    {template.name}
                  </h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mb-3">
                    {template.nameTl}
                  </p>
                  
                  {template.isPremium ? (
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-green-600 dark:text-green-400">
                        ₱{template.price}
                      </span>
                      {PREMIUM_ENABLED ? (
                        <Button size="sm" variant="primary">
                          Buy
                        </Button>
                      ) : (
                        <span className="text-xs text-amber-600 dark:text-amber-400 flex items-center gap-1">
                          <Clock className="w-3 h-3" />
                          Soon
                        </span>
                      )}
                    </div>
                  ) : (
                    <span className="text-sm text-gray-500 dark:text-gray-400 flex items-center gap-1">
                      <Check className="w-4 h-4 text-green-500" />
                      Free
                    </span>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        {/* Payment Methods Section */}
        <section className="mb-16">
          <div className="text-center mb-8">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
              Payment Methods
            </h2>
            <p className="text-gray-600 dark:text-gray-400">
              Secure and convenient payment options for Filipinos
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            <Card variant="bordered">
              <CardContent className="p-6 text-center">
                <div className="w-16 h-16 bg-blue-100 dark:bg-blue-900/30 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Smartphone className="w-8 h-8 text-blue-600 dark:text-blue-400" />
                </div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  GCash / Maya
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Pay instantly using your e-wallet. Most convenient for Filipinos.
                </p>
              </CardContent>
            </Card>

            <Card variant="bordered">
              <CardContent className="p-6 text-center">
                <div className="w-16 h-16 bg-purple-100 dark:bg-purple-900/30 rounded-full flex items-center justify-center mx-auto mb-4">
                  <CreditCard className="w-8 h-8 text-purple-600 dark:text-purple-400" />
                </div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  Credit / Debit Card
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Visa, Mastercard, and other major cards accepted.
                </p>
              </CardContent>
            </Card>

            <Card variant="bordered">
              <CardContent className="p-6 text-center">
                <div className="w-16 h-16 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Building2 className="w-8 h-8 text-green-600 dark:text-green-400" />
                </div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  Bank Transfer
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Direct bank transfer via InstaPay or PESONet.
                </p>
              </CardContent>
            </Card>
          </div>

          <div className="mt-6 text-center">
            <p className="text-sm text-gray-500 dark:text-gray-400 flex items-center justify-center gap-2">
              <Shield className="w-4 h-4" />
              Secured by PayMongo • PCI-DSS Compliant
            </p>
          </div>
        </section>

        {/* FAQ Section */}
        <section>
          <div className="text-center mb-8">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            <Card variant="bordered">
              <CardContent className="p-6">
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  Do I need to pay to use Resibilis?
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  No! Resibilis is free to use. You can generate and download receipts without paying anything. Premium templates are optional upgrades.
                </p>
              </CardContent>
            </Card>

            <Card variant="bordered">
              <CardContent className="p-6">
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  Is my payment secure?
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Yes! We use PayMongo, a BSP-licensed payment processor. Your payment information is encrypted and never stored on our servers.
                </p>
              </CardContent>
            </Card>

            <Card variant="bordered">
              <CardContent className="p-6">
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  Can I get a refund?
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Template purchases are non-refundable since they are digital products. However, contact us if you have issues and we'll help resolve them.
                </p>
              </CardContent>
            </Card>

            <Card variant="bordered">
              <CardContent className="p-6">
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  How do I access purchased templates?
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  After purchase, templates are automatically added to your account. Just sign in and select your template when creating receipts.
                </p>
              </CardContent>
            </Card>
          </div>
        </section>
      </div>
    </main>
  );
}
