import { Header, Footer } from '@/components/layout';

export const metadata = {
  title: 'Terms of Service | Resibilis',
  description: 'Terms of Service for Resibilis Receipt Generator',
  alternates: {
    canonical: 'https://resibilis.vercel.app/terms',
  },
  openGraph: {
    title: 'Terms of Service | Resibilis',
    description: 'Terms of Service for Resibilis Receipt Generator',
    url: 'https://resibilis.vercel.app/terms',
    type: 'website',
  },
};

export default function TermsPage() {
  return (
    <>
      <Header user={null} />
      <main className="flex-1 container mx-auto px-4 py-8 max-w-4xl">
        <article className="prose dark:prose-invert max-w-none">
          <h1>Terms of Service</h1>
          <p className="text-gray-500 dark:text-gray-400">
            Last Updated: November 30, 2025
          </p>

          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using Resibilis (&quot;the Service&quot;), you agree to be bound by these 
              Terms of Service. If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              Resibilis is a receipt generator web application that allows users to:
            </p>
            <ul>
              <li>Create professional receipts for products and services</li>
              <li>Download receipts as PNG or PDF files</li>
              <li>Save and manage receipt history (registered users)</li>
              <li>Maintain a catalog of products/services (registered users)</li>
              <li>Access premium templates (subscribers)</li>
            </ul>
          </section>

          <section>
            <h2>3. User Accounts</h2>
            
            <h3>3.1 Registration</h3>
            <p>
              You may use basic features without registration. To save receipts and access 
              additional features, you must create an account using Google OAuth.
            </p>

            <h3>3.2 Account Responsibility</h3>
            <p>
              You are responsible for maintaining the confidentiality of your account and for 
              all activities that occur under your account.
            </p>

            <h3>3.3 Accurate Information</h3>
            <p>
              You agree to provide accurate, current, and complete information when creating 
              an account and generating receipts.
            </p>
          </section>

          <section>
            <h2>4. Acceptable Use</h2>
            <p>You agree NOT to use Resibilis to:</p>
            <ul>
              <li>Generate fraudulent or fake receipts</li>
              <li>Create receipts for illegal transactions</li>
              <li>Misrepresent transactions or amounts</li>
              <li>Violate any applicable laws, including tax regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Attempt to hack, disrupt, or compromise our systems</li>
              <li>Use automated systems to scrape or access the Service</li>
            </ul>
            <p>
              <strong>Legal Disclaimer:</strong> Receipts generated by Resibilis are for 
              record-keeping purposes. For official tax documents (OR/SI), please use 
              BIR-registered systems. Users are responsible for compliance with Philippine 
              tax laws and BIR regulations.
            </p>
          </section>

          <section>
            <h2>5. Free and Premium Services</h2>
            
            <h3>5.1 Free Tier</h3>
            <ul>
              <li>Unlimited receipt generation (guest mode)</li>
              <li>Basic receipt template</li>
              <li>PNG/PDF download</li>
              <li>Receipt history (registered users)</li>
            </ul>

            <h3>5.2 Premium Features (₱50 one-time or subscription)</h3>
            <ul>
              <li>Premium receipt templates</li>
              <li>Custom branding options</li>
              <li>Additional receipt dimensions</li>
              <li>Priority support</li>
            </ul>

            <h3>5.3 Payment and Refunds</h3>
            <p>
              Premium features are purchased as one-time payments or subscriptions. Refunds 
              may be requested within 7 days of purchase if the features do not work as described.
            </p>
          </section>

          <section>
            <h2>6. Intellectual Property</h2>
            
            <h3>6.1 Our Content</h3>
            <p>
              Resibilis is created and maintained by Clark Jim Gabiota. The Resibilis name, logo,
              templates, and software are owned by Clark Jim Gabiota and protected by applicable
              intellectual property laws.
            </p>

            <h3>6.2 Your Content</h3>
            <p>
              You retain ownership of the content you create (customer names, items, etc.). 
              By using our Service, you grant us a limited license to process and store this 
              content to provide the Service.
            </p>
          </section>

          <section>
            <h2>7. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY 
              KIND, EXPRESS OR IMPLIED. We do not warrant that:
            </p>
            <ul>
              <li>The Service will be uninterrupted or error-free</li>
              <li>Receipts generated will meet specific legal requirements</li>
              <li>The Service will be suitable for your specific needs</li>
            </ul>
          </section>

          <section>
            <h2>8. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, RESIBILIS SHALL NOT BE LIABLE FOR ANY 
              INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM:
            </p>
            <ul>
              <li>Your use or inability to use the Service</li>
              <li>Errors in generated receipts</li>
              <li>Loss of data or business interruption</li>
              <li>Unauthorized access to your account</li>
            </ul>
          </section>

          <section>
            <h2>9. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Resibilis from any claims, damages, 
              or expenses arising from your use of the Service, violation of these Terms, 
              or violation of any rights of third parties.
            </p>
          </section>

          <section>
            <h2>10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for 
              violation of these Terms. You may delete your account at any time through 
              your account settings.
            </p>
          </section>

          <section>
            <h2>11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws 
              of the Republic of the Philippines. Any disputes shall be resolved in the 
              courts of the Philippines.
            </p>
          </section>

          <section>
            <h2>12. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Continued use of the 
              Service after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2>13. Contact</h2>
            <p>
              For questions about these Terms, contact me at:
            </p>
            <ul>
              <li>
                <strong>Website:</strong>{' '}
                <a
                  href="https://mitakashime.vercel.app"
                  target="_blank"
                  rel="noreferrer"
                >
                  https://mitakashime.vercel.app
                </a>
              </li>
            </ul>
          </section>

          <section>
            <h2>14. Severability</h2>
            <p>
              If any provision of these Terms is found to be unenforceable, the remaining 
              provisions will continue in full force and effect.
            </p>
          </section>
        </article>
      </main>
      <Footer />
    </>
  );
}
